
const Home = () => {
    return ( 
        <div className="home">
            <h3>你好！ 我是DiDi，我姓陳</h3>
            <h3>歡迎來到我唯一正式的網站</h3>
            <h2>我的故事</h2>
            <p> Lorem ipsum dolor sit, amet consectetur adipisicing elit. In magnam ullam temporibus inventore recusandae sint dicta ipsam modi, nesciunt porro maxime debitis distinctio nemo facilis quo placeat molestias voluptas error illum at nobis est autem voluptatibus. Perferendis amet nulla officiis, repellendus qui debitis consectetur dicta deserunt corporis similique inventore voluptates accusantium nesciunt nisi aliquam dolore! Ex debitis repudiandae sequi ad doloribus architecto beatae quidem. Recusandae fugit suscipit eaque reprehenderit iure ipsum molestiae pariatur consequatur vero! Nam velit ullam saepe, inventore placeat obcaecati labore minus ea, reiciendis possimus sequi, numquam sed illo exercitationem beatae. Eum, minus at. Quam aliquam dicta possimus, dolor earum illo asperiores, harum itaque officiis cum error fugit odio, sed blanditiis accusantium. Officiis accusamus iste excepturi minus fugit quam quod molestias beatae illo explicabo. Voluptatibus quos unde cum incidunt hic, consectetur repellat natus illo? Laudantium, quasi optio quam nulla rem est asperiores beatae ipsam quos amet ratione laborum, debitis aperiam eveniet earum, dolorem ad. Doloribus nostrum, sed delectus adipisci porro consequatur fuga, vitae et, corrupti nam dolorum hic! Voluptatem adipisci perferendis similique quo cumque voluptas, impedit architecto iure alias consequuntur, enim ratione? Alias cupiditate eius officia sapiente in sit iure architecto animi voluptatibus ipsam, voluptatum ipsum inventore natus totam necessitatibus consectetur ea eum molestiae exercitationem. Aperiam nostrum commodi, reprehenderit corrupti sequi consectetur itaque. Architecto dolorem, temporibus corrupti, error natus eaque nihil in, iste consequatur adipisci qui fugiat magnam neque facere esse similique nobis iusto consectetur maiores sunt earum nisi laudantium assumenda! Dolores rerum itaque aliquam, quibusdam laudantium corrupti, dignissimos asperiores consequuntur, aliquid cumque assumenda delectus voluptatem a optio perferendis necessitatibus. Totam sint voluptates unde voluptatem labore eaque amet? Ea odit iure placeat, quam recusandae deleniti, quasi voluptatum consequatur debitis ad vitae cupiditate! </p>
            <h2>關鍵事實</h2>
            <p> Lorem ipsum dolor sit, amet consectetur adipisicing elit. In magnam ullam temporibus inventore recusandae sint dicta ipsam modi, nesciunt porro maxime debitis distinctio nemo facilis quo placeat molestias voluptas error illum at nobis est autem voluptatibus. Perferendis amet nulla officiis, repellendus qui debitis consectetur dicta deserunt corporis similique inventore voluptates accusantium nesciunt nisi aliquam dolore! Ex debitis repudiandae sequi ad doloribus architecto beatae quidem. Recusandae fugit suscipit eaque reprehenderit iure ipsum molestiae pariatur consequatur vero! Nam velit ullam saepe, inventore placeat obcaecati labore minus ea, reiciendis possimus sequi, numquam sed illo exercitationem beatae. Eum, minus at. Quam aliquam dicta possimus, dolor earum illo asperiores, harum itaque officiis cum error fugit odio, sed blanditiis accusantium. Officiis accusamus iste excepturi minus fugit quam quod molestias beatae illo explicabo. Voluptatibus quos unde cum incidunt hic, consectetur repellat natus illo? Laudantium, quasi optio quam nulla rem est asperiores beatae ipsam quos amet ratione laborum, debitis aperiam eveniet earum, dolorem ad. Doloribus nostrum, sed delectus adipisci porro consequatur fuga, vitae et, corrupti nam dolorum hic! Voluptatem adipisci perferendis similique quo cumque voluptas, impedit architecto iure alias consequuntur, enim ratione? Alias cupiditate eius officia sapiente in sit iure architecto animi voluptatibus ipsam, voluptatum ipsum inventore natus totam necessitatibus consectetur ea eum molestiae exercitationem. Aperiam nostrum commodi, reprehenderit corrupti sequi consectetur itaque. Architecto dolorem, temporibus corrupti, error natus eaque nihil in, iste consequatur adipisci qui fugiat magnam neque facere esse similique nobis iusto consectetur maiores sunt earum nisi laudantium assumenda! Dolores rerum itaque aliquam, quibusdam laudantium corrupti, dignissimos asperiores consequuntur, aliquid cumque assumenda delectus voluptatem a optio perferendis necessitatibus. Totam sint voluptates unde voluptatem labore eaque amet? Ea odit iure placeat, quam recusandae deleniti, quasi voluptatum consequatur debitis ad vitae cupiditate! </p>
        </div>
     );
}
 
export default Home;